# 00 · Data acquisition & provenance

This notebook downloads and caches **every** real, open-access dataset used in the
rapamycin multi-omics series, and records its provenance. Run it first.

**Layers & sources**

| Layer | Dataset | Repository |
|-------|---------|-----------|
| Target / mechanism | Rapamycin → FKBP1A/MTOR | ChEMBL (CHEMBL413) |
| Transcriptomics | GSE131754 mouse liver RNA-seq (rapamycin vs control) | NCBI GEO — Tyshkovskiy *et al.*, *Cell Metab* 2019 |
| Pharmacogenomics | GDSC1 Temsirolimus IC50 (~970 cancer cell lines) | Therapeutics Data Commons |
| Proteomics | PXD067812 rapamycin-treated DLBCL, TMT-18plex global + phospho | PRIDE/ProteomeXchange |

All data are public. Nothing here constitutes clinical efficacy evidence; these are
secondary analyses of published molecular data.

In [1]:
import os, sys, json, gzip, re, warnings
from pathlib import Path
import numpy as np
import pandas as pd
warnings.filterwarnings("ignore")

# Resolve project root whether run from notebooks/ or project root.
CWD = Path.cwd()
PROJ = CWD.parent if CWD.name == "notebooks" else CWD
RAW = PROJ / "data" / "raw"
PROC = PROJ / "data" / "processed"
FIG = PROJ / "figures"
for d in (RAW, PROC, FIG):
    d.mkdir(parents=True, exist_ok=True)

import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams["figure.dpi"] = 110
sns.set_style("whitegrid")
print("Project root:", PROJ)

Project root: /Users/jinmo/Documents/GitHub/Series1/Jin001_Docking/rapamycin_multiomics

## 1 · Transcriptomics — GEO GSE131754 (rapamycin vs control RNA-seq)

In [2]:
import urllib.request
GSE_URL = ("https://ftp.ncbi.nlm.nih.gov/geo/series/GSE131nnn/"
           "GSE131754/suppl/GSE131754_Interventions_assigned_reads.txt.gz")
gse_path = RAW / "GSE131754_Interventions_assigned_reads.txt.gz"
if not gse_path.exists():
    print("Downloading GSE131754 count matrix ...")
    urllib.request.urlretrieve(GSE_URL, gse_path)
counts = pd.read_csv(gse_path, sep="\t", index_col=0)
print("RNA-seq counts:", counts.shape, "(genes x samples)")
rap = [c for c in counts.columns if c.startswith("RAP")]
con = [c for c in counts.columns if c.startswith("CON")]
print(f"Rapamycin samples: {len(rap)} | Control samples: {len(con)}")
counts.iloc[:3, :6]

RNA-seq counts: (43629, 78) (genes x samples)
Rapamycin samples: 12 | Control samples: 12

,ACA_12m_F_1,ACA_12m_F_2,ACA_12m_F_3,ACA_12m_M_1,ACA_12m_M_2,ACA_12m_M_3
GENE_ID,,,,,,
ENSMUSG00000102693,0,0,0,0,0,0
ENSMUSG00000064842,0,0,0,0,0,0
ENSMUSG00000051951,0,0,0,0,2,0

## 2 · Proteomics — PRIDE PXD067812 (rapamycin-treated DLBCL, TMT-18plex)

In [3]:
MZTAB_URL = ("https://ftp.pride.ebi.ac.uk/pride/data/archive/2025/09/"
             "PXD067812/P1426-TMT18-10-F.mzTab")
mztab_path = RAW / "PXD067812.mzTab"
if not mztab_path.exists():
    print("Downloading PXD067812 mzTab (~85 MB) ...")
    urllib.request.urlretrieve(MZTAB_URL, mztab_path)
print("mzTab cached:", round(mztab_path.stat().st_size / 1e6, 1), "MB")

# TMT-18plex channel -> condition map (from PRIDE 'Table 1')
TMT_MAP = {
    1: ("DMSO", "DMSO_1"), 2: ("DMSO", "DMSO_2"), 3: ("DMSO", "DMSO_3"),
    4: ("Rapamycin_24h", "Rapa24h_1"), 5: ("Rapamycin_24h", "Rapa24h_2"), 6: ("Rapamycin_24h", "Rapa24h_3"),
    7: ("Rapamycin_48h", "Rapa48h_1"), 8: ("Rapamycin_48h", "Rapa48h_2"), 9: ("Rapamycin_48h", "Rapa48h_3"),
    10: ("MasterMix", "MasterMix"),
}
pd.DataFrame([(k, *v) for k, v in TMT_MAP.items()],
             columns=["assay", "condition", "sample"]).to_csv(PROC / "proteomics_channel_map.csv", index=False)
print("Saved channel map -> proteomics_channel_map.csv")

mzTab cached: 85.0 MB
Saved channel map -> proteomics_channel_map.csv

## 3 · Pharmacogenomics — GDSC1 drug response via Therapeutics Data Commons

In [4]:
from tdc.multi_pred import DrugRes
gdsc = DrugRes(name="GDSC1", path=str(RAW))
df = gdsc.get_data()
print("GDSC1:", df.shape, "| drugs:", df['Drug_ID'].nunique(), "| cell lines:", df['Cell Line_ID'].nunique())
# Temsirolimus = CCI-779, a rapamycin ester prodrug / mTOR inhibitor
tem = df[df['Drug_ID'].astype(str).str.contains('Temsirolimus', case=False)].copy()
tem.to_csv(PROC / "gdsc_temsirolimus.csv", index=False)
print("Temsirolimus response rows:", tem.shape[0])
tem.head()

Downloading...

  0%|          | 0.00/140M [00:00<?, ?iB/s]

  0%|          | 17.4k/140M [00:00<20:55, 112kiB/s]

  0%|          | 69.6k/140M [00:00<10:59, 213kiB/s]

  0%|          | 174k/140M [00:00<06:19, 370kiB/s]

  0%|          | 400k/140M [00:00<03:22, 693kiB/s]

  1%|          | 836k/140M [00:00<01:50, 1.26MiB/s]

  1%|          | 1.31M/140M [00:01<01:24, 1.66MiB/s]

  2%|▏         | 2.50M/140M [00:01<00:45, 3.02MiB/s]

  2%|▏         | 3.42M/140M [00:01<00:38, 3.59MiB/s]

  3%|▎         | 4.81M/140M [00:01<00:30, 4.51MiB/s]

  4%|▎         | 5.25M/140M [00:02<00:44, 3.02MiB/s]

  6%|▌         | 8.66M/140M [00:02<00:19, 6.75MiB/s]

  7%|▋         | 9.92M/140M [00:02<00:19, 6.65MiB/s]

  8%|▊         | 11.2M/140M [00:02<00:19, 6.58MiB/s]

  9%|▉         | 12.5M/140M [00:02<00:19, 6.59MiB/s]

 10%|▉         | 13.9M/140M [00:03<00:19, 6.61MiB/s]

 11%|█         | 15.2M/140M [00:03<00:18, 6.63MiB/s]

 12%|█▏        | 16.5M/140M [00:03<00:19, 6.41MiB/s]

 13%|█▎        | 17.9M/140M [00:03<00:17, 6.83MiB/s]

 13%|█▎        | 18.9M/140M [00:03<00:19, 6.29MiB/s]

 14%|█▍        | 19.8M/140M [00:04<00:20, 5.89MiB/s]

 15%|█▍        | 20.8M/140M [00:04<00:21, 5.64MiB/s]

 15%|█▌        | 21.7M/140M [00:04<00:23, 4.97MiB/s]

 16%|█▌        | 22.7M/140M [00:04<00:22, 5.19MiB/s]

 17%|█▋        | 23.4M/140M [00:04<00:24, 4.73MiB/s]

 17%|█▋        | 24.1M/140M [00:05<00:26, 4.43MiB/s]

 18%|█▊        | 24.9M/140M [00:05<00:27, 4.24MiB/s]

 18%|█▊        | 25.6M/140M [00:05<00:27, 4.13MiB/s]

 19%|█▉        | 26.4M/140M [00:05<00:28, 4.06MiB/s]

 19%|█▉        | 27.2M/140M [00:05<00:28, 4.03MiB/s]

 20%|█▉        | 27.6M/140M [00:06<00:34, 3.24MiB/s]

 20%|██        | 28.7M/140M [00:06<00:27, 4.10MiB/s]

 21%|██        | 29.2M/140M [00:06<00:30, 3.70MiB/s]

 21%|██        | 29.8M/140M [00:06<00:31, 3.46MiB/s]

 22%|██▏       | 30.4M/140M [00:06<00:33, 3.31MiB/s]

 22%|██▏       | 31.0M/140M [00:07<00:34, 3.20MiB/s]

 22%|██▏       | 31.6M/140M [00:07<00:34, 3.16MiB/s]

 23%|██▎       | 32.2M/140M [00:07<00:34, 3.11MiB/s]

 23%|██▎       | 32.8M/140M [00:07<00:34, 3.10MiB/s]

 24%|██▍       | 33.4M/140M [00:07<00:34, 3.09MiB/s]

 24%|██▍       | 34.1M/140M [00:08<00:34, 3.06MiB/s]

 25%|██▍       | 34.7M/140M [00:08<00:34, 3.10MiB/s]

 25%|██▌       | 35.4M/140M [00:08<00:33, 3.15MiB/s]

 26%|██▌       | 36.0M/140M [00:08<00:33, 3.16MiB/s]

 26%|██▌       | 36.7M/140M [00:08<00:32, 3.19MiB/s]

 27%|██▋       | 37.3M/140M [00:09<00:31, 3.25MiB/s]

 27%|██▋       | 38.0M/140M [00:09<00:31, 3.25MiB/s]

 28%|██▊       | 38.7M/140M [00:09<00:30, 3.29MiB/s]

 28%|██▊       | 39.3M/140M [00:09<00:30, 3.30MiB/s]

 28%|██▊       | 40.0M/140M [00:09<00:30, 3.31MiB/s]

 29%|██▉       | 40.7M/140M [00:10<00:29, 3.33MiB/s]

 29%|██▉       | 41.3M/140M [00:10<00:29, 3.37MiB/s]

 30%|██▉       | 42.0M/140M [00:10<00:29, 3.37MiB/s]

 30%|███       | 42.7M/140M [00:10<00:28, 3.38MiB/s]

 31%|███       | 43.4M/140M [00:10<00:28, 3.37MiB/s]

 31%|███▏      | 44.0M/140M [00:11<00:28, 3.40MiB/s]

 32%|███▏      | 44.7M/140M [00:11<00:28, 3.39MiB/s]

 32%|███▏      | 45.4M/140M [00:11<00:27, 3.41MiB/s]

 33%|███▎      | 46.1M/140M [00:11<00:27, 3.40MiB/s]

 33%|███▎      | 46.8M/140M [00:11<00:27, 3.40MiB/s]

 34%|███▍      | 47.4M/140M [00:12<00:27, 3.42MiB/s]

 34%|███▍      | 48.1M/140M [00:12<00:27, 3.40MiB/s]

 35%|███▍      | 48.8M/140M [00:12<00:27, 3.38MiB/s]

 35%|███▌      | 49.5M/140M [00:12<00:26, 3.40MiB/s]

 36%|███▌      | 50.1M/140M [00:12<00:26, 3.40MiB/s]

 36%|███▌      | 50.8M/140M [00:13<00:26, 3.41MiB/s]

 37%|███▋      | 51.5M/140M [00:13<00:26, 3.40MiB/s]

 37%|███▋      | 52.2M/140M [00:13<00:26, 3.39MiB/s]

 38%|███▊      | 52.9M/140M [00:13<00:25, 3.40MiB/s]

 38%|███▊      | 53.5M/140M [00:13<00:25, 3.39MiB/s]

 39%|███▊      | 54.2M/140M [00:14<00:25, 3.41MiB/s]

 39%|███▉      | 54.9M/140M [00:14<00:25, 3.40MiB/s]

 40%|███▉      | 55.6M/140M [00:14<00:24, 3.42MiB/s]

 40%|████      | 56.3M/140M [00:14<00:24, 3.43MiB/s]

 41%|████      | 57.0M/140M [00:14<00:24, 3.44MiB/s]

 41%|████      | 57.6M/140M [00:15<00:24, 3.44MiB/s]

 42%|████▏     | 58.3M/140M [00:15<00:23, 3.45MiB/s]

 42%|████▏     | 59.0M/140M [00:15<00:23, 3.48MiB/s]

 42%|████▏     | 59.4M/140M [00:15<00:27, 2.95MiB/s]

 43%|████▎     | 60.0M/140M [00:15<00:26, 3.01MiB/s]

 43%|████▎     | 60.5M/140M [00:16<00:28, 2.80MiB/s]

 43%|████▎     | 61.0M/140M [00:16<00:28, 2.78MiB/s]

 44%|████▍     | 61.5M/140M [00:16<00:28, 2.74MiB/s]

 44%|████▍     | 62.1M/140M [00:16<00:28, 2.75MiB/s]

 45%|████▍     | 62.7M/140M [00:16<00:28, 2.76MiB/s]

 45%|████▌     | 63.2M/140M [00:17<00:27, 2.82MiB/s]

 45%|████▌     | 63.8M/140M [00:17<00:27, 2.81MiB/s]

 46%|████▌     | 64.4M/140M [00:17<00:26, 2.88MiB/s]

 46%|████▋     | 65.0M/140M [00:17<00:25, 2.92MiB/s]

 47%|████▋     | 65.7M/140M [00:17<00:25, 2.99MiB/s]

 47%|████▋     | 66.3M/140M [00:18<00:24, 3.06MiB/s]

 48%|████▊     | 66.9M/140M [00:18<00:23, 3.08MiB/s]

 48%|████▊     | 67.6M/140M [00:18<00:23, 3.14MiB/s]

 49%|████▊     | 68.2M/140M [00:18<00:22, 3.18MiB/s]

 49%|████▉     | 68.9M/140M [00:18<00:22, 3.22MiB/s]

 50%|████▉     | 69.5M/140M [00:19<00:21, 3.28MiB/s]

 50%|████▉     | 70.2M/140M [00:19<00:21, 3.32MiB/s]

 50%|█████     | 70.9M/140M [00:19<00:20, 3.35MiB/s]

 51%|█████     | 71.6M/140M [00:19<00:20, 3.36MiB/s]

 51%|█████▏    | 72.2M/140M [00:19<00:20, 3.40MiB/s]

 52%|█████▏    | 72.9M/140M [00:20<00:19, 3.43MiB/s]

 52%|█████▏    | 73.6M/140M [00:20<00:19, 3.44MiB/s]

 53%|█████▎    | 74.3M/140M [00:20<00:19, 3.45MiB/s]

 53%|█████▎    | 75.0M/140M [00:20<00:19, 3.44MiB/s]

 54%|█████▍    | 75.7M/140M [00:20<00:18, 3.48MiB/s]

 54%|█████▍    | 76.4M/140M [00:21<00:18, 3.47MiB/s]

 55%|█████▍    | 77.1M/140M [00:21<00:18, 3.50MiB/s]

 55%|█████▌    | 77.8M/140M [00:21<00:17, 3.49MiB/s]

 56%|█████▌    | 78.5M/140M [00:21<00:17, 3.51MiB/s]

 56%|█████▋    | 79.2M/140M [00:21<00:17, 3.53MiB/s]

 57%|█████▋    | 79.9M/140M [00:22<00:17, 3.52MiB/s]

 57%|█████▋    | 80.6M/140M [00:22<00:16, 3.53MiB/s]

 58%|█████▊    | 81.3M/140M [00:22<00:16, 3.52MiB/s]

 58%|█████▊    | 82.0M/140M [00:22<00:16, 3.54MiB/s]

 59%|█████▉    | 82.7M/140M [00:22<00:16, 3.52MiB/s]

 59%|█████▉    | 83.4M/140M [00:23<00:16, 3.54MiB/s]

 60%|█████▉    | 84.1M/140M [00:23<00:15, 3.54MiB/s]

 60%|██████    | 84.4M/140M [00:23<00:18, 2.97MiB/s]

 61%|██████    | 85.1M/140M [00:23<00:17, 3.16MiB/s]

 61%|██████    | 85.6M/140M [00:23<00:18, 2.94MiB/s]

 61%|██████▏   | 86.1M/140M [00:24<00:19, 2.85MiB/s]

 62%|██████▏   | 86.7M/140M [00:24<00:18, 2.83MiB/s]

 62%|██████▏   | 87.2M/140M [00:24<00:19, 2.74MiB/s]

 62%|██████▏   | 87.8M/140M [00:24<00:18, 2.87MiB/s]

 63%|██████▎   | 88.4M/140M [00:24<00:18, 2.80MiB/s]

 63%|██████▎   | 89.0M/140M [00:25<00:18, 2.84MiB/s]

 64%|██████▎   | 89.5M/140M [00:25<00:17, 2.88MiB/s]

 64%|██████▍   | 90.2M/140M [00:25<00:16, 3.13MiB/s]

 65%|██████▍   | 90.8M/140M [00:25<00:15, 3.13MiB/s]

 65%|██████▌   | 91.4M/140M [00:25<00:15, 3.15MiB/s]

 66%|██████▌   | 92.0M/140M [00:25<00:15, 3.17MiB/s]

 66%|██████▌   | 92.7M/140M [00:26<00:15, 2.99MiB/s]

 66%|██████▋   | 93.3M/140M [00:26<00:14, 3.33MiB/s]

 67%|██████▋   | 94.0M/140M [00:26<00:13, 3.33MiB/s]

 67%|██████▋   | 94.7M/140M [00:26<00:13, 3.35MiB/s]

 68%|██████▊   | 95.3M/140M [00:26<00:13, 3.36MiB/s]

 68%|██████▊   | 96.0M/140M [00:27<00:13, 3.36MiB/s]

 69%|██████▉   | 96.7M/140M [00:27<00:12, 3.38MiB/s]

 69%|██████▉   | 97.4M/140M [00:27<00:12, 3.42MiB/s]

 70%|██████▉   | 98.0M/140M [00:27<00:12, 3.44MiB/s]

 70%|███████   | 98.6M/140M [00:27<00:11, 3.74MiB/s]

 70%|███████   | 99.0M/140M [00:28<00:13, 3.19MiB/s]

 71%|███████   | 99.4M/140M [00:28<00:11, 3.49MiB/s]

 71%|███████   | 99.8M/140M [00:28<00:11, 3.52MiB/s]

 71%|███████▏  | 100M/140M [00:28<00:12, 3.11MiB/s]

 72%|███████▏  | 101M/140M [00:28<00:10, 3.62MiB/s]

 72%|███████▏  | 101M/140M [00:28<00:10, 3.62MiB/s]

 72%|███████▏  | 102M/140M [00:28<00:12, 3.18MiB/s]

 73%|███████▎  | 102M/140M [00:28<00:10, 3.72MiB/s]

 73%|███████▎  | 103M/140M [00:29<00:10, 3.68MiB/s]

 73%|███████▎  | 103M/140M [00:29<00:11, 3.21MiB/s]

 74%|███████▍  | 104M/140M [00:29<00:10, 3.63MiB/s]

 74%|███████▍  | 104M/140M [00:29<00:10, 3.53MiB/s]

 74%|███████▍  | 104M/140M [00:29<00:10, 3.29MiB/s]

 75%|███████▍  | 105M/140M [00:29<00:09, 3.70MiB/s]

 75%|███████▌  | 105M/140M [00:29<00:09, 3.56MiB/s]

 75%|███████▌  | 106M/140M [00:29<00:10, 3.34MiB/s]

 76%|███████▌  | 106M/140M [00:30<00:09, 3.77MiB/s]

 76%|███████▌  | 107M/140M [00:30<00:09, 3.59MiB/s]

 76%|███████▋  | 107M/140M [00:30<00:09, 3.39MiB/s]

 77%|███████▋  | 108M/140M [00:30<00:08, 3.77MiB/s]

 77%|███████▋  | 108M/140M [00:30<00:09, 3.58MiB/s]

 77%|███████▋  | 109M/140M [00:30<00:09, 3.42MiB/s]

 78%|███████▊  | 109M/140M [00:30<00:08, 3.81MiB/s]

 78%|███████▊  | 110M/140M [00:30<00:08, 3.59MiB/s]

 78%|███████▊  | 110M/140M [00:31<00:08, 3.43MiB/s]

 79%|███████▊  | 111M/140M [00:31<00:07, 3.79MiB/s]

 79%|███████▉  | 111M/140M [00:31<00:08, 3.55MiB/s]

 79%|███████▉  | 111M/140M [00:31<00:08, 3.43MiB/s]

 80%|███████▉  | 112M/140M [00:31<00:07, 3.82MiB/s]

 80%|████████  | 112M/140M [00:31<00:07, 3.56MiB/s]

 80%|████████  | 113M/140M [00:31<00:08, 3.40MiB/s]

 81%|████████  | 113M/140M [00:32<00:07, 3.64MiB/s]

 81%|████████  | 114M/140M [00:32<00:07, 3.60MiB/s]

 81%|████████▏ | 114M/140M [00:32<00:07, 3.30MiB/s]

 82%|████████▏ | 115M/140M [00:32<00:07, 3.65MiB/s]

 82%|████████▏ | 115M/140M [00:32<00:07, 3.61MiB/s]

 82%|████████▏ | 116M/140M [00:32<00:07, 3.35MiB/s]

 83%|████████▎ | 116M/140M [00:32<00:06, 3.70MiB/s]

 83%|████████▎ | 117M/140M [00:32<00:06, 3.64MiB/s]

 83%|████████▎ | 117M/140M [00:33<00:07, 3.32MiB/s]

 84%|████████▍ | 118M/140M [00:33<00:06, 3.73MiB/s]

 84%|████████▍ | 118M/140M [00:33<00:06, 3.63MiB/s]

 84%|████████▍ | 118M/140M [00:33<00:06, 3.32MiB/s]

 85%|████████▍ | 119M/140M [00:33<00:05, 3.78MiB/s]

 85%|████████▌ | 119M/140M [00:33<00:05, 3.65MiB/s]

 85%|████████▌ | 120M/140M [00:33<00:06, 3.32MiB/s]

 86%|████████▌ | 121M/140M [00:34<00:05, 3.84MiB/s]

 86%|████████▌ | 121M/140M [00:34<00:05, 3.69MiB/s]

 86%|████████▋ | 121M/140M [00:34<00:05, 3.37MiB/s]

 87%|████████▋ | 122M/140M [00:34<00:04, 3.88MiB/s]

 87%|████████▋ | 122M/140M [00:34<00:04, 3.70MiB/s]

 87%|████████▋ | 123M/140M [00:34<00:05, 3.37MiB/s]

 88%|████████▊ | 123M/140M [00:34<00:04, 3.96MiB/s]

 88%|████████▊ | 124M/140M [00:34<00:04, 3.75MiB/s]

 88%|████████▊ | 124M/140M [00:35<00:04, 3.39MiB/s]

 89%|████████▉ | 125M/140M [00:35<00:03, 4.04MiB/s]

 89%|████████▉ | 125M/140M [00:35<00:03, 3.81MiB/s]

 90%|████████▉ | 126M/140M [00:35<00:04, 3.42MiB/s]

 90%|█████████ | 126M/140M [00:35<00:03, 4.17MiB/s]

 90%|█████████ | 127M/140M [00:35<00:03, 3.94MiB/s]

 91%|█████████ | 127M/140M [00:35<00:03, 3.51MiB/s]

 91%|█████████ | 128M/140M [00:35<00:02, 4.27MiB/s]

 91%|█████████▏| 128M/140M [00:36<00:03, 3.94MiB/s]

 92%|█████████▏| 129M/140M [00:36<00:03, 3.57MiB/s]

 92%|█████████▏| 130M/140M [00:36<00:02, 4.40MiB/s]

 93%|█████████▎| 130M/140M [00:36<00:02, 3.96MiB/s]

 93%|█████████▎| 130M/140M [00:36<00:02, 3.63MiB/s]

 93%|█████████▎| 131M/140M [00:36<00:02, 3.77MiB/s]

 94%|█████████▍| 132M/140M [00:37<00:02, 3.91MiB/s]

 95%|█████████▍| 133M/140M [00:37<00:01, 4.01MiB/s]

 95%|█████████▌| 134M/140M [00:37<00:01, 4.10MiB/s]

 96%|█████████▌| 135M/140M [00:37<00:01, 4.20MiB/s]

 97%|█████████▋| 136M/140M [00:37<00:01, 4.28MiB/s]

 97%|█████████▋| 137M/140M [00:38<00:00, 4.35MiB/s]

 98%|█████████▊| 138M/140M [00:38<00:00, 4.46MiB/s]

 99%|█████████▊| 138M/140M [00:38<00:00, 4.52MiB/s]

 99%|█████████▉| 139M/140M [00:38<00:00, 4.64MiB/s]

100%|█████████▉| 140M/140M [00:38<00:00, 4.74MiB/s]

100%|██████████| 140M/140M [00:38<00:00, 3.61MiB/s]

Loading...

Done!

GDSC1: (177310, 5) | drugs: 208 | cell lines: 958
Temsirolimus response rows: 911

,Drug_ID,Drug,Cell Line_ID,Cell Line,Y
112800,Temsirolimus,C[C@@H]1CC[C@H]2C[C@@H](/C(=C/C=C/C=C/[C@H](C[...,MC-CAR,"[3.23827250519154, 2.98225419469807, 10.235490...",-3.957970
112801,Temsirolimus,C[C@@H]1CC[C@H]2C[C@@H](/C(=C/C=C/C=C/[C@H](C[...,PFSK-1,"[7.78071324341182, 2.75325311612598, 9.9601374...",-4.281551
112802,Temsirolimus,C[C@@H]1CC[C@H]2C[C@@H](/C(=C/C=C/C=C/[C@H](C[...,A673,"[7.301344403901299, 2.89053310182054, 9.922489...",-2.361187
112803,Temsirolimus,C[C@@H]1CC[C@H]2C[C@@H](/C(=C/C=C/C=C/[C@H](C[...,ES3,"[8.690197905033282, 3.0914731119366, 9.9924871...",-3.289580
112804,Temsirolimus,C[C@@H]1CC[C@H]2C[C@@H](/C(=C/C=C/C=C/[C@H](C[...,ES5,"[8.233101127037282, 2.82468731112752, 10.01588...",-3.488040

## 4 · Target / mechanism — ChEMBL (downloaded live in notebook 01)

In [5]:
import requests
r = requests.get("https://www.ebi.ac.uk/chembl/api/data/molecule/CHEMBL413.json", timeout=60)
mol = r.json()
print("ChEMBL molecule:", mol.get("pref_name"), "| CHEMBL413")
print("Max phase (approval):", mol.get("max_phase"))

ChEMBL molecule: SIROLIMUS | CHEMBL413
Max phase (approval): 4.0

## 5 · Provenance summary

In [6]:
provenance = pd.DataFrame([
    dict(layer="Target/mechanism", dataset="ChEMBL CHEMBL413 (rapamycin/sirolimus)",
         source="EMBL-EBI ChEMBL v34", access="REST API"),
    dict(layer="Transcriptomics", dataset="GSE131754 mouse liver RNA-seq (RAP=12 vs CON=12)",
         source="NCBI GEO; Tyshkovskiy 2019 Cell Metab 10.1016/j.cmet.2019.06.018", access="GEO FTP"),
    dict(layer="Pharmacogenomics", dataset="GDSC1 Temsirolimus IC50",
         source="Therapeutics Data Commons (DrugRes)", access="PyTDC"),
    dict(layer="Proteomics", dataset="PXD067812 SU-DHL-4 rapamycin TMT-18plex",
         source="PRIDE/ProteomeXchange", access="PRIDE FTP (mzTab)"),
])
provenance.to_csv(PROC / "provenance.csv", index=False)
provenance

,layer,dataset,source,access
0,Target/mechanism,ChEMBL CHEMBL413 (rapamycin/sirolimus),EMBL-EBI ChEMBL v34,REST API
1,Transcriptomics,GSE131754 mouse liver RNA-seq (RAP=12 vs CON=12),NCBI GEO; Tyshkovskiy 2019 Cell Metab 10.1016/...,GEO FTP
2,Pharmacogenomics,GDSC1 Temsirolimus IC50,Therapeutics Data Commons (DrugRes),PyTDC
3,Proteomics,PXD067812 SU-DHL-4 rapamycin TMT-18plex,PRIDE/ProteomeXchange,PRIDE FTP (mzTab)

**Done.** All datasets are cached under `data/raw/` and key extracts under `data/processed/`.
Proceed to `01_target_mechanism.ipynb`.